### ISSUE TITLE
🐛[BUG] : Mouse animation missing  on Register page 

### ISSUE THREAD

**Issue by akash70629** [ankit071105/Ticket-Booking#1052]
### Description

Mouse animation missing  on register page 

### Screenshots

![image](https://github.com/user-attachments/assets/27096047-5fdb-4cb4-bbd2-51247bd4b869)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Added the necessary HTML and JavaScript code to implement the mouse animation on the login page. Also ensured the required CSS is present in the main.css file.

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/1055


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by akash70629** [comment]
> Hello, I tried to fix the issue
> 
> This is what I did:
> 
> Added the necessary HTML and JavaScript code to implement the mouse animation on the login page. Also ensured the required CSS is present in the main.css file.
> 
> I also created pull request: #1055
> 
> Caution
> 
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.
> 
> This bug was fixed for free by Latta AI - https://latta.ai/ourmission
> 
> If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

Now what is this !!!???😂😂😂😂 @ankit071105
