### ISSUE TITLE
[BUG]  UI fixed of sell page form

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ankit071105/Ticket-Booking#1059]
### Description

in your website in sell.html page the submit button ui is not good its get outside the button also the plaqceholder is not  good ui they are so big as comapre to the from also  below the seat number and price placeholder the3 submit button also not aligned properly i want to fix this

### Screenshots

![WhatsApp Image 2024-11-07 at 22 47 29_dc05f6b1](https://github.com/user-attachments/assets/18493d6a-c509-469d-8058-c70c6f1dae67)

### Any additional information?

a

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Improve submit button UI, adjust placeholder sizes, and fix alignment of elements in the sell ticket form.

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/1064


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
