### ISSUE TITLE
[BUG] The footer is embedded in the sell section and the alignment is not proper❗

### ISSUE THREAD

**Issue by shriyadindi** [ankit071105/Ticket-Booking#1104]
### Description

The footer is embedded in the sell section and the alignment is not proper❗

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Moved the footer outside of the sell-ticket section and adjusted its positioning to ensure proper alignment at the bottom of the page.

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/1106


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
