### ISSUE TITLE
[BUG] Navbar issue in the contributors page - dual logo and alignment issue

### ISSUE THREAD

**Issue by shriyadindi** [ankit071105/Ticket-Booking#1105]
### Description

Navbar issue in the contributors page - dual logo and alignment issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Resolved the dual logo issue and improved navbar alignment on the contributors page. Removed duplicate logo, adjusted styling for better responsiveness, and ensured consistent layout across different screen sizes.

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/1107


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
