### ISSUE TITLE
BACKEND ISSUE

### ISSUE THREAD

**Issue by ankit071105** [ankit071105/Ticket-Booking#401]
### Description

The project functions as a mediator between sellers and buyers of tickets. Here's a detailed summary of the backend functionality needed:

 # Seller Ticket Listing:

When a user lists their ticket in the Seller Section, the backend should automatically adjust the price.
The listed ticket price will be 50 rupees less than the original price of the ticket.
# For example
 if a seller lists a ticket originally priced at 500 rupees, the system will list it at 450 rupees in the Seller Section.

# Buyer Ticket Listing:

After a ticket is listed by a seller, the backend will post the same ticket in the Buyer Section.
However, in the Buyer Section, the ticket should be listed at a higher price: 100 rupees more than the original price.
# For instance,
 if a ticket originally costs 500 rupees, it will be posted at 600 rupees in the Buyer Section.

### Any additional information?

The backend will ensure that:

A price reduction is applied when a ticket is listed in the Seller Section.
A price increase is applied when the same ticket is posted in the Buyer Section.
This process creates a margin where sellers are paid less for their tickets, and buyers purchase them at a premium.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SumitSahu44** [comment]
hey @ankit071105 assign this to me i will do it within 2day

**Comment by ankit071105** [comment]
> hey @ankit071105 assign this to me i will do it within 2day

okay show me solution i will assgin you

**Comment by Osank31** [comment]
Did you mean you want to enable the submit ticket functionality which is not yet working?

**Comment by ankit071105** [comment]
yeah @Osank31

**Comment by ankit071105** [comment]
@T-Rahul-prabhu-38  can you solve this issue ???

**Comment by T-Rahul-prabhu-38** [comment]
i tried this , im sorry im not able to finish

**Comment by Osank31** [comment]
@ankit071105  Could you please assign this issue to me? Thanks!

**Comment by ankit071105** [comment]
> @ankit071105 Could you please assign this issue to me? Thanks!

understand the issue  in detailed  and show me some examples that data is storing and showing in the website there .

**Comment by Osank31** [comment]
Ok.

**Comment by Osank31** [comment]
Here is how the program works

![Screenshot 2024-10-19 004446](https://github.com/user-attachments/assets/ff33755c-e3fc-4ae8-80ae-50804552fdb3)

First user is supposed to enter the details for the ticket to be sold

The handleTicketSubmission is run which collects form details

Then i added this peice of code

![Screenshot 2024-10-19 005949](https://github.com/user-attachments/assets/60c3f097-c8bc-4334-89f3-014f9a1cf835)

This code sends a request to server.js requesting to accept the raw data.

![Screenshot 2024-10-19 010037](https://github.com/user-attachments/assets/dd48b0c6-1e4d-474f-96f8-958a1ca21180)

This peice of code sends the code into the database


![Screenshot 2024-10-19 010021](https://github.com/user-attachments/assets/f73beb3a-d6b6-4cd4-8370-d471b91a94a7)

This is how the seller schema looks like

![Screenshot 2024-10-19 010106](https://github.com/user-attachments/assets/c5af4424-8c73-4677-89a8-79c7834c2115)

This is how the final data looks like in the database


@ankit071105 If you are satisfied with my solution please assign me this issue so that i can work in this properly and work on fixing the selling for bus tickets as well. ThankYou.

**Comment by ankit071105** [comment]
All data is getting stored and showed in buy.html page ?? @Osank31

**Comment by ankit071105** [comment]
If user want to buy he can get the ticket which is listed by seller user @Osank31  ?

**Comment by Osank31** [comment]
No i did not add that functionality yet. But i can do it.

**Comment by Osank31** [comment]
This is only how the data will be stored, the original code stored the data at web browser storage but instead it stores in mongoDb

**Comment by Osank31** [comment]
For said functionality i can use mongodb aggregation pipeline and then use GET method to display it to frontend.

**Comment by ankit071105** [comment]
> For said functionality i can use mongodb aggregation pipeline and then use GET method to display it to frontend. @ankit071105

yes you can

**Comment by Osank31** [comment]
Here i added the code
![Screenshot 2024-10-20 204018](https://github.com/user-attachments/assets/bc1c3cd8-cda9-4bc8-ac03-b116ff80b1df)
And got the result on page like
![Screenshot 2024-10-20 203954](https://github.com/user-attachments/assets/7310a7e5-5e40-4bf6-967b-fa56e971d99e)

I will be doing the rest bug fixes in this code after i get assigned @ankit071105. ThankYou

**Comment by Osank31** [comment]
@ankit071105 will you assign me this?

**Comment by ankit071105** [comment]
> @ankit071105 will you assign me this?

Have you completed what The projects Want ??

**Comment by ankit071105** [comment]
I have assigned this to You Add Perfect Works

**Comment by Osank31** [comment]
Ok

**Comment by ankit071105** [comment]
> I will do it in 4-5 days

okay under 5 day generate a pr because  event are ending in 5 days
