### ISSUE TITLE
[BUG] Missing Twitter Handle At front page (About ) As well as on the Contact Us page .

### ISSUE THREAD

**Issue by an07th09** [ankit071105/Ticket-Booking#862]
### Description

The twitter handle remails empty . Logo is not visible neither the link .
![Screenshot 2024-11-01 113558](https://github.com/user-attachments/assets/73feb4bc-bb59-4c73-825d-786a4c5adc7f)
![Screenshot 2024-11-01 113620](https://github.com/user-attachments/assets/614da6c9-0f1f-412f-93df-401ef257ff24)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've updated the footer section in the index.html file to fix the issue with the Twitter handle and logo not being visible. I've added the correct Twitter icon and link, and ensured all social media icons are properly displayed and linked.

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/863


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
