### ISSUE TITLE
[BUG] website is not responsive

### ISSUE THREAD

**Issue by srivishnu2805** [ankit071105/Ticket-Booking#880]
### Description

the whole website is not responsive so it needed to be fixed 

### Screenshots

![image](https://github.com/user-attachments/assets/81ca02b5-e8c7-4b4e-b79f-2c6c69751b58)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai1** [comment]
Hello, I tried to fix the issue

This is what I did:
I've made several changes to improve the responsiveness of the website. Here's a summary of the modifications:

1. Updated the CSS to use more flexible units and responsive design patterns.
2. Added media queries to adjust layouts for different screen sizes.
3. Modified the navbar to be more mobile-friendly.
4. Adjusted the slider and ticket card layouts for better mobile viewing.
5. Improved form and button responsiveness.

Here are some key code changes:

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/882


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.**

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
