### ISSUE TITLE
[BUG] Buy ticket code changes

### ISSUE THREAD

**Issue by saumyayadav25** [ankit071105/Ticket-Booking#884]
### Description

I have seen many people just copy pasting code in the files leading to redundancy of code files. I came across your buy me ticket html file which has double Doctype html/ body. 
If you want i can work on managing your code in a standard format leading to better understanding of code and avoiding duplicate content.

### Screenshots

<img width="1439" alt="Screenshot 2024-11-01 at 6 47 27 PM" src="https://github.com/user-attachments/assets/c3117ad4-e8d2-421d-be54-da909f79654b">
<img width="1440" alt="Screenshot 2024-11-01 at 6 47 13 PM" src="https://github.com/user-attachments/assets/c9d9b19c-c1d9-4a39-8042-feba20a3368d">

### Any additional information?

I can work on this issue. 
Please assign level 3 as it will require whole redesigning of page and structuring the code.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by lattaai1** [comment]
Hello, I tried to fix the issue

This is what I did:
I have refactored the buy_bus_ticket.html and buy_train_ticket.html files to remove redundancy and improve code structure. The main changes include:

1. Consolidated the common HTML structure into a single file.
2. Created separate sections for bus and train tickets.
3. Updated the JavaScript to handle both ticket types.
4. Improved accessibility by adding ARIA labels and roles.
5. Removed duplicate DOCTYPE and body tags.

Here's a summary of the changes:

I also created pull request: https://github.com/ankit071105/Ticket-Booking/pull/885


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.**

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
